[package]
name = "verkle_trie"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
bitvec = "0.21.1"
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves", default-features = false, features = ["curve"] }
thiserror = "1.0.24"
rand_core = { version = "0.5", features = ["getrandom"] }
rand_chacha = { version = "0.2.1", default-features = false }
rayon = { version = "1.3" }

sha2 = "0.9.3"
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }

merlin = "3.0.0"
hex = "0.4.3"
slotmap = { version = "1.0", features = ["serde"] }

[dev-dependencies]
